### ISSUE TITLE
Travis is not pushing new Docker images

### ISSUE THREAD

**Issue by ghost** [multiarch/ubuntu-core#14]
Due to invalid username or password. Are you guys aware of this fact?

E.g., https://travis-ci.org/multiarch/ubuntu-core/jobs/383687152#L447

```
1.02s$ if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO; fi
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

**Comment by meyskens** [comment]
@moul  looks like the login in travis is missing :/

**Comment by moul** [comment]
I added them (again?), and relaunched a build

wait and see

**Comment by moul** [comment]
the build: https://travis-ci.org/multiarch/ubuntu-core/builds/405356342

**Comment by moul** [comment]
LGTM: https://travis-ci.org/multiarch/ubuntu-core/jobs/405356343

**Comment by meyskens** [comment]
Seems to work! Thanks @moul
