### ISSUE TITLE
Update images

### ISSUE THREAD

**Issue by meyskens** [multiarch/ubuntu-core#2]
Can the xenial image be rebuilt, some apps will not like that it was based on a beta build

``````
## Your distribution, identified as "Ubuntu Xenial Xerus (development branch)", is a pre-release version of Ubuntu.```
``````

**Comment by moul** [comment]
Hey @meyskens, sorry for the delay

It's in progress

**Comment by meyskens** [comment]
I currently use my own 😛 `meyskens/ubuntu-mulitarch`

**Comment by moul** [comment]
:)

**Comment by moul** [comment]
pushed :shipit:

**Comment by lobradov** [comment]
Can we rebuild?
I believe last images are built using 16.04.1, and current is 16.04.3...

(I'll actually open a new ticket)
